apiVersion: apps/v1
kind: Deployment
metadata:
  name: m1
  namespace: ramji
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m1 
  template:
    metadata:
      labels:
        app: m1 
    spec:
      containers:
      - name: m1 
        image: katacoda/docker-http-server:latest
        ports:
        - containerPort: 80
